### PR TITLE
Json ld

### PR DESCRIPTION
**Pull request by siglun**

### CODE REVIEW

**Comment by siglun** [comment]
The data is in directory nested-corpus. It is the *.jsonld files that we need to review at this time.

**Review by tokee — CHANGES_REQUESTED** [review]
Overall it looks very usable. I like the flexibility of the fields, such as `keywords` containing both literals and `DefinedTerm`s.


Shouldn't it be `identifier` everywhere, instead of `id`? Personally I prefer `id`, but we're playing by schema.org rules here.


The IDs follow the principle of generic-to-specific parts: `<overall type>!<collection>!<collection specific sub path>!<id>!<sub path and id>`. Two examples from the JSON-LD files:

 * `letters!judsam!2011!mar!dsa!object2674!disposable!subrecord!d6e176`
 * `images!luftfo!2011!maj!luftfoto!object322504`

The devil is in the details, so

 1. What does `letters` and `images` mean? What is the value of the information in the ID? If one is requesting a `letter`, does it say anything about what can be expected of the content?
 2. The collection names seems very legacy-ish: `judsam` and `luftfo` is what it is, but the date stuff like `2011!mar` seems superfluous and `luftfo!2011!maj!luftfoto` is repeating the same information. What about simplifying to `judsam!object2674!disposable!subrecord!d6e176` and `luftfoto!object322504`?
 3. Why is `!` used as delimiter in IDs? It means that IDs must be escaped (not just quoted) in the term and visually it is unconventional. I get that `/` does not work well with REST calls, but what about `-`?
 4. Related we should write down rules for IDs, such as "`[a-zA-Z0-9_-]` only".
 5. It seems obvious that we have a single authoritative ID for each object, but how do we represent alternative IDs as separate from that? I think you have done so in `tystrup-soroe.jsonld`, but I am not sure about the principle.


Could we make `Collection` a mandatory field? I know we can infer it from the `id`, but it seems like such an important thing that it should be explicit.


When we represent images as sub parts of an object, it makes a lot of sense to provide an URL to data about the image. At the same time, it would also make sense to provide URLs to a preview version, a larger scale version, a full size version and a general IIPImage endpoint (the `image_preview`, `image_full` and `iiif`-fields in the Solr schema). Can we represent that in JSON-LD? There is `thumbnailURL`, but what about the generic IIIF-URL?


The `MediaObject`s in `encoding`s uses `contentURL` to point to a JSON-representation. schema.org says that [contentURL](https://schema.org/contentUrl) is for "Actual bytes of the media object, for example the image file or video file.". Shouldn't we use `url` for the JSON and `contentURL` for a link to the image server?


I see that `license` is a defined field for JSON-LD. We should have a fixed set of those (represented as URLs) and it should be mandatory (with the default being "unresolved, personal viewing only" written in legalese)


Should we add some kind of "Metadata delivery time" field for provenance? It helps with trouble shooting, such as when you have 2 different representations of the same object. Or maybe better a "Last updated in the backend" timestamp?

**Comment by siglun** [comment]
I will change those things in the files, so that we remember them when it is time to implement. I haven't found any placeholder for administrative data (like datetime created, revised, exported or whatever). But I belive it is useful to have when making front-end work as well.

**Comment by siglun** [comment]
>    What does letters and images mean? What is the value of the information in the ID? If one is requesting a letter, does it say >     anything about what can be expected of the content?

Those are from the URIs used in the current digital editions, AKA COP. They are mainly used for statistics as required by auditors (Riksrevisionen), who requires that access logs are structured by media type

>     The collection names seems very legacy-ish: judsam and luftfo is what it is, but the date stuff like 2011!mar seems 
>     superfluous and luftfo!2011!maj!luftfoto is repeating the same information. What about simplifying to 
>     judsam!object2674!disposable!subrecord!d6e176 and luftfoto!object322504?

Year and month is syntactic sugar and isn't used anywhere in the software. The disposable subrecord is completely redundant, it was for the purpose of the nested solr records where it had a (hypothetical) function.

I want that we should be able to redirect permanently (301) old COP URIs after release of DS

>     Why is ! used as delimiter in IDs? It means that IDs must be escaped (not just quoted) in the term and visually it is 
>     unconventional. I get that / does not work well with REST calls, but what about -?

It was used in the SOLR manual at some places. It is an  inheritance from the previous nested solr records (don't do regex solr search...) from a few weeks ago. I'll go back to '/'!!!!

>     Related we should write down rules for IDs, such as "[a-zA-Z0-9_-] only".

I have Backus-Naur syntaxes for current COP URIs somewhere. Haven't found them yet.

>     It seems obvious that we have a single authoritative ID for each object, but how do we represent alternative IDs as separate >     from that? I think you have done so in tystrup-soroe.jsonld, but I am not sure about the principle.

I'm not sure either. It seems that schema.org wants an url in each hash {}. id seems optional. That is I suppose the LOD philosophy emerging

**Review by jorntx — APPROVED** [review]
From a frontend perspective this looks good and certainly contains enough object information for os to work with and 'pass on'. Approved.

**Comment by siglun** [comment]
I go directly to implementation now: I'll bear those comments in mind while implementing.

We must make a new reviews, perhaps one per media type.

**Pull request merged**
